const Recommendskills = [
    // Broad Categories
    "Web Development",
    "Frontend Development",
    "Backend Development",
    "Full-Stack Development",
    "Mobile Development",
    "AI & Machine Learning",
    "Cloud Computing",
    "Cybersecurity",
    "Blockchain & Web3",
    "DevOps",
    "Database Management",
    "API Development",
    "Software Development",
    "System Design",
    "Data Science",
    "Game Development",

    // Programming Languages
    "JavaScript",
    "TypeScript",
    "Python",
    "Java",
    "C++",
    "C#",
    "Go",
    "Ruby",
    "Swift",
    "Kotlin",
    "Dart",
    "Rust",

    // Frontend Development
    "HTML",
    "CSS",
    "SASS",
    "Tailwind CSS",
    "Bootstrap",
    "React.js",
    "Next.js",
    "Vue.js",
    "Nuxt.js",
    "Angular",
    "Svelte",
    "Redux",
    "Zustand",
    "Recoil",
    "PHP",
    "Laravel",
    "Blade",
    "Twig",

    // Backend Development
    "Node.js",
    "Express.js",
    "NestJS",
    "Django",
    "Flask",
    "FastAPI",
    "Ruby on Rails",
    "Spring Boot",
    "ASP.NET",

    // Databases
    "MongoDB",
    "PostgreSQL",
    "MySQL",
    "Firebase",
    "Redis",
    "DynamoDB",
    "SQLite",

    // API Development
    "REST APIs",
    "GraphQL",
    "tRPC",
    "gRPC",
    "WebSockets",
    "OAuth",
    "JWT Authentication",
    "API Rate Limiting",
    "Postman",

    // Cloud Computing & DevOps
    "AWS",
    "Azure",
    "Google Cloud Platform (GCP)",
    "DigitalOcean",
    "Cloudflare",
    "Docker",
    "Kubernetes",
    "Terraform",
    "Serverless",
    "CI/CD",
    "GitHub Actions",
    "Jenkins",
    "Vercel",
    "Netlify",

    // Security & Authentication
    "Encryption",
    "SSL/TLS",
    "OAuth2",
    "SAML",
    "JWT",
    "2FA",
    "Web Security",
    "Ethical Hacking",
    "Penetration Testing",

    // Mobile Development
    "React Native",
    "Flutter",
    "Swift (iOS)",
    "Kotlin (Android)",
    "Dart",

    // AI & Machine Learning
    "Artificial Intelligence",
    "Machine Learning",
    "Deep Learning",
    "Natural Language Processing (NLP)",
    "Computer Vision",
    "OpenAI API",
    "LangChain",
    "Hugging Face",
    "TensorFlow",
    "PyTorch",
    "LLMs",

    // Blockchain & Web3
    "Blockchain",
    "Ethereum",
    "Solidity",
    "Smart Contracts",
    "Polygon",
    "IPFS",
    "Metamask",
    "Hardhat",
    "Truffle",

    // Other Tools & Technologies
    "Git",
    "GitHub",
    "GitLab",
    "Bitbucket",
    "Webpack",
    "Bun",
    "Vite",
    "ESLint",
    "Figma",
    "PostgreSQL",
    "Stripe",
    "Twilio",
    "Google Analytics",
  ];
  export {Recommendskills};